
# Notes Atelier Rmarkdown 

Autrices et auteurs : 

   * Joris Huguenin
   * Clara Gritti
   * Camila Leandro
   * Nathalie Zeballos
   * Océane Cobelli
Ce document est une prise de notes collaboratives de l'atelier Rmarkdown effectué au CEFE le 25 mars 2022.



## Pourquoi utiliser Rmarkdown ?

Utiliser word, notamment pour des documents longs et complexes, peut rapidement être plus couteux en termes d'effort.



[https://bookdown.org/yihui/rmarkdown/](https://bookdown.org/yihui/rmarkdown/)



WISYMIG \& WISYMIM (sont sur un bâteau ? ) What you see is what you get (word, openoffice) VS What you see is what you mean (Rmarkdown). Sous R, nous pouvons écrire un script qui peut être exporté en .rmd. La fonction knitr (petit bouton sous Rstudio avec une pelotte de laine) permet ensuite de compiler et exporter sous différents formats (.tex (et .pdf), .docx, .html).

Pour plus d'informations [https://stateofther.github.io/finistR2018/atelier3\_advancedrmd.html](https://stateofther.github.io/finistR2018/atelier3\_advancedrmd.html) 

[https://ismayc.github.io/rbasics-book/5-rmdanal.html](https://ismayc.github.io/rbasics-book/5-rmdanal.html)



Avantage d'utiliser le package memoiR au lieu de simplement Markdown: Création d'un ensemble de fichiers (cf plus bas) pour gérer plus facilement des documents plus longs/complexes (thèse, livre), avec un fichier rmd par chapitre (gain de temps pour knitter, interchanger position des chp etc). 



## Profil des utilisateurs de l'atelier

   * scripts R : 8 TB / 5 BOF [sur 13 partcipants]
   * projets R : 10 oui /3 non  [Joris nous parle importance de faire des projets à chaque début de projet, notamment pour l'utilisation de Git]
   * Git (Github, GitLab, ...) : 4 [le CNRS va déployer un GitLab]
   * BibTex :  10 oui / 3 non [Logiciels type Zotero,... // memoiR utilise très bien les documents .bib]
   * Rmarkdown : 8.5 oui / 4.5 non
   * LaTeX : 1 oui / 12 non
   * Beamer : [outil pour construire des présentations ; avantages : facile à faire / désaventages : moins intuitif que powerpoint]
   * MemoiR : personne ne l'a déjà utilisé


## Compilation dans Rstudio

Écrire un fichier .rmd avec un peu de texte, de l'import de data, et un résultat sous forme de tableau ou graphe. 

Déposer les fichiers .rmd  ici : [https://mycore.core-cloud.net/index.php/s/cdMB0VkkrYplVk3](https://mycore.core-cloud.net/index.php/s/cdMB0VkkrYplVk3) et les annexes dans les dossiers correspondants.



### Le fichier .rmd

La cheatsheet : [https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

Le guide de référence : [https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf) 



### Comment gére-t-on la bibliographie ? 

citr : package pour faire sa bibliographie (une recherche du nom de l'auteur permet d'insérer la réfernce). Pour en savoir plus : [https://github.com/crsh/citr](https://github.com/crsh/citr) Après l'installation du package, il peut être nécessaire de quitter/rouvrir le projet pour que l'option "Insert citation" apparaisse dans le volet de "Addins". /!\ Le package peut ne pas être disponible pour certaines versions de R. 

On n'est pas obligé d'installer citr si on a précisé le fichier .bib dans le YAML, on peut utiliser @... (fonctionne en mode "compas", pas en mode "normal"). Avec le @, on accède au .bib et à la bibliothèque principale de zotero (pas les bi



Aternative, utiliser les clés de citation bibTex avec les logiciels de gestion de bibliographie : 

Zotero -> extension Better BibTex [[https://retorque.re/zotero-better-bibtex/](https://retorque.re/zotero-better-bibtex/)], crée une clé de citation pour chaque biblio -> extraction d'un fichier bibtex lu par R (fichier .bib en UTF-8) -> on le range dans un dossier /biblio dans notre projet R -> pour l'importer dans le fichier Rmd on écrit dans l'en-tête du document (YAML) : "bibliography : biblio/nomdufichier.bib" ; on peut aussi ajouter des options pour les citations avec biblatexoptions

Pour Mendeley il y a cette aide en ligne [https://blog.mendeley.com/2011/10/25/howto-use-mendeley-to-create-citations-using-latex-and-bibtex/](https://blog.mendeley.com/2011/10/25/howto-use-mendeley-to-create-citations-using-latex-and-bibtex/). Sinon sélectionner les citations qui vous intéressent (CTRL + A sélectionne tout dans le dossier choisi), puis Edit -> Exporter.



Le choix du style de citations peut se faire dans les options au début. 



### YAML ? 

Partie du haut qui donne les caractéristiques générales du document (titre, auteur, date, gestion de la bibliographie...).



### chunck ?

[https://yihui.org/knitr/options/#cache](https://yihui.org/knitr/options/#cache)



Pour mettre du code dans le document

Il est possible d'utiliser le raccourci ctrl+alt+i pour insérer rapidement un chunk. 



### la gestion du cache

Dans un premier "chunk" qui peut s'appeler *setup *on peut ajouter un certain nombre de directives pour l'ensemble des chunks. Par exemple, comment afficher à chaque fois les images. Pour le cache c'est ici qu'on va introduire deux paramètres, qui permettent que le calcul se fasse qu'une seule fois et que le résultat soit enregistré, ainsi lors d'une prochaine compilation, il n'y pas nécessité de tout recalculer (ça fait gagner du temps !).

- cache = TRUE

- cache.lazy = FALSE)

[https://bioinfo-fr.net/maitrisez-cache-de-rmarkdown](https://bioinfo-fr.net/maitrisez-cache-de-rmarkdown)





### Mise en page

Visualier le rendu sans knitter : petite icone compas en haut à droite ("Switch to visual markdown editor"). 

** blablabla ** --> rendu en gras : **blablabla**

'mean(data$colonneA)' --> sort le résultat de la fonction demandée, ici la moyenne de la colonne A du fichier data



### Et les tableaux ?



avec kable, kableExtra et flextable



kable = le package de base pour afficher des tableaux

kableExtra = package amélioré qui permet de mettre en forme les tableaux



### Les équations mathématiques ? 

dans MemoiR : packages amsmaths et amssyms (?), chargés dans le template.tex



## Écrire un article

Rmd -> from template [choix parmi un éventail (i.e. PNAS, Plos, Elsevier publications...]



install.packages("rticles")

library(rticles)

[https://pagedown.rbind.io/](https://pagedown.rbind.io/)



## Écrire un mémoire

Nouveau projet -> Markdown (choisi memoiR -> document type memoir)

Beaucoup de fichier et dossiers se créent ; ça peut impressioner, mais ça veut juste dire qu'il a "déjà travaillé". Rien que compiler l'exemple permet d'avoir un guide pour créer son propre mémoire (ça prends plusieurs minutes).



Intérêt de faire des chapitres : mieux gérer un doc long (manuscrit de thèse par exemple), inverser ordre des chapitres rapidement (juste changer nom du fichier et R recompile dans le nouvel ordre), temps de compilation qui diminue.



chapitrer son document

Le référencement croisé

[https://ericmarcon.github.io/memoiR/gallery/memoir/bookdown\_gitbook/index.html](https://ericmarcon.github.io/memoiR/gallery/memoir/bookdown\_gitbook/index.html) 

[https://ericmarcon.github.io/travailleR/](https://ericmarcon.github.io/travailleR/)  [Excellente référence pour travailler sur R (pas que sur Markdown)]



Plusieurs fichiers créés, dont :

- index --> YAML que dans ce fichier (préciser page de garde créée en tant que pdf au préalable)

   * - précision de la langue (pour accès aux accents etc), de l'abstract, des mots-clés dans ce fichier ; Il est en effet important de noter -langage: english (ou bien le langage utilisé dans le document)
   * - 1er chunk : NE PAS MODIFIER !
   * - 2ème chunk qui permet de gérer le style des figures
   * - 3ème chunk : knitr options --> mettre la librairie ici
   * - Glossaire : permet de faire le lien avec les titres de nos différents chapitres
   * -unnumbered (ne pas commencer la pagination à cette section)
- syntax

- getting start

- etc.





Organisation de notre mémoire : le + efficace c'est de faire 1 fichier par chapitre, la numérotation des chapitres va permettre de compiler le tout dans le bon ordre (mais après, ça reste une préférence personnelle, on peut mettre tous les chapitres dans le même fichier si on préfére, ça sera un peu + long à compiler)



Références internes au document à mettre entre {}



Dans le sous-dossier latex

- template.tex -> package intégrés pour écrire des formules mathématiques, options pour la bibliographie, options gitbook avec titre et url personnels (researchgate...)

Indiquer la langue qu'on utilise (dans template.tex) : sert à charger les bons caractères (notamment pour les accents) et possibilité d'avoir un correcteur orthographique

Template.tex = tout est déjà réglé en language LaTex, bien pratique si on veut juste modifier qqs options

- Fichiers after\_body.tex = pour ajouter des annexes en fin de rapport



Package tinytex : gère le langage LaTex dans R


